### ISSUE TITLE
<委託:快速鍵入常用字>

### ISSUE THREAD

**Issue by TheEndKiller** [HelloZhangf/Skript#4]
任何想法都可以提出 , 收不收費取決於花不花我太多時間\

委託腳本名稱: <快速鍵入常用字>

委託人名稱: <你老婆>

委託腳本內容:
<輸入/chat會顯示常用語縮寫清單，看到想要的可以輸入代號或自定的名稱，例如打/chat N會在公頻發話NMSL CNMB，
並且可以自訂指令，例如輸入/chat N後先說NMSL CNMB之後會自動被系統mute 5分鐘 >
</chat>
<>
<>
<>

聯絡方式: <你老婆> <秘密>

=======================選填
從何得知我: <你長得太帥>

對我教學講義的看法:
<文章寫得蠻清楚的，很不錯>
<希望能補充越來越多東西>
<加油>

給我的建議:
<可以試著接案鍛鍊自己>
<可以把套件介紹慢慢加進來>
<生意興隆#>

**Comment by HelloZhangf** [comment]
hello , 謝謝您的委託 , 由於您的內容模糊不清 , 我不知該從何下手
希望您可以再說清楚些

**Comment by TheEndKiller** [comment]
主要指令:/chat /chat <代號或名稱>
/chat可以顯示所有縮寫的清單
在SK內可自行編寫的設置
配置例:
ID: 1
Name: <N>
Say: self 你輸入了N給你NMSL CNMB
Command: /mute <PlayerName> 300 說髒話

/chat清單格式範例:
輸入/chat <ID或名稱>使用快速輸入
ID | 名稱 | 發送對話 | 目標
0 | N | NMSL CNMB | 所有人
1 | 服 | 服主好帥我愛你 | 自己

舉例:
玩家MAJOJO輸入 /chat顯示了:
輸入/chat <ID或名稱>使用快速輸入
ID | 名稱 | 發送對話 | 目標
0 | N | NMSL CNMB | 所有人
1 | 服 | 服主好帥我愛你 | 自己
在他的聊天室，
MAJOJO輸入 /chat 0
聊天室全部人看到 <MAJOJO>NMSL CNMB
然後MAJOJO就被伺服器自動禁言了

註解:
<PlayerName>為PlaceHolder，會自動轉換為輸入的玩家名稱，並越過權限執行
all跟self在

格式範例:
ID: <自行輸入數字ID>
Name: <英文或數字名稱>
Say: <self 這裡輸入文字>(發送文字給你自己) /  <all 這裡輸入文字>(以你的名子發送給全部玩家)  / none(不顯示任何對話)
Command: <輸入指令>

**Comment by HelloZhangf** [comment]
下禮拜開工 ~

**Comment by HelloZhangf** [comment]
完成咯~~

腳本名稱: 標籤系統(快速發送常用訊息)
作者: HelloZhangf
發布時間: 
21 : 40 : 21
週六, 2020年8月15日


使用版本: 1.9 ~ 1.16
下載網址: https://reurl.cc/OqbN6A

備註:
抱歉拉~ 拖了有點久 , 因為真的有正式絆住 

當你第一次讀取時 , 會將您說的 "N" 會發送CNMB NMSL 的標籤預設註冊了~
說的人會被禁言 五分鐘~

除了N這個標籤以外 , 其他註冊的新標籤都沒辦法加入輸入時執行的指令
因為我還沒想要一個比較好的寫法~~
等待下次更新我就會推出了~

第一次發布的版本 , 功能不是很齊全 , 還希望您的收下

注意事項我都寫在sk檔案內了~
